# originally from https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hashicorp-vault
  labels:
    app: vault
    tier: infrastructure
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: infrastructure
    matchExpressions:
      - {key: tier, operator: In, values: [infrastructure]}
  template:
    metadata:
      labels:
        app: vault
        tier: infrastructure
    spec:
      containers:
      - name: hashicorp-vault
        image: alpine:3.8
        command: [ "/bin/ash", "-c", "wget https://releases.hashicorp.com/vault/0.11.3/vault_0.11.3_linux_amd64.zip && unzip vault_0.11.3_linux_amd64.zip; ./vault server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=roottoken" ]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          #value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          value: env
        ports:
        - containerPort: 80