kind: Service
apiVersion: v1
metadata:
  name: vault-service
spec:
  selector:
    app: vault
  ports:
  - protocol: TCP
    port: 8200
    # vault default listening TCP port
    targetPort: 8200
  type: LoadBalancer